# Generated by Django 5.0.4 on 2024-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctnumber',
            name='maxNumber',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
