# Generated by Django 4.2.11 on 2024-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_correctnumber_guessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctnumber',
            name='numberOfGuesses',
            field=models.IntegerField(default=0),
        ),
    ]
